# Generated by Django 4.1.1 on 2023-01-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_remove_movie_country_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(blank=True, to='viewer.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='acting',
            field=models.ManyToManyField(blank=True, related_name='acting_in_movie', to='viewer.movie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='artist_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='awards',
            field=models.ManyToManyField(blank=True, to='viewer.award'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='directing',
            field=models.ManyToManyField(blank=True, related_name='directing_movie', to='viewer.movie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='surname',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
