# Generated by Django 4.1.1 on 2023-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_movie_images_alter_movie_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movies', to='viewer.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='viewer.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='movies', to='viewer.image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='staff', to='viewer.award'),
        ),
    ]
