# Generated by Django 4.1.1 on 2023-02-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
